import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/AuthProvider";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>
        <AuthProvider>
          <Navbar />
          <div>
            <Toaster
              richColors
              position="bottom-right"
              toastOptions={{
                classNames: {
                  toast: "min-h-[80px] px-6 py-4 text-base",
                },
              }}
            />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
