import { Inter } from "next/font/google";
import { Metadata } from "next"; 
import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/AuthProvider";
import { Toaster } from "sonner";
import "../globals.css"; // Ensure this is the correct path to your global styles

// Import the Inter font from Google Fonts
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap", // Helps with better font rendering
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Optional: Add the preload link for faster font loading */}
        <link
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${inter.className} antialiased`}>
        <AuthProvider>
          <Navbar />
          <div className="min-h-screen bg-blue-50">
            <Toaster
              richColors
              position="bottom-right"
              toastOptions={{
                classNames: {
                  toast: "p-4 text-base",
                },
              }}
            />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
